### ISSUE TITLE
Discussion: Securing mechanism for VCs

### ISSUE THREAD

**Issue by rghiorghisor** [creator-assertions/identity-assertion#111]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------
In the [4.9 Securing Mechanisms](https://www.w3.org/TR/vc-data-model-2.0/#securing-mechanisms) section of  [Verifiable Credentials Data Model v2.0](https://www.w3.org/TR/vc-data-model-2.0) there are specified two means of securing Verifiable Credentials. 

This discussion revolves around: "_Which one of these two should Identity Assertion support (for now)?_"

### Why specify either in the first place?
As these securing mechanisms are part of the W3C VC specification, one would wonder why does Identity Assertion needs to support one (or both) explicitly?

Specifying one option will make it easier for verifiers to implement VC verification mechanisms, thus  encouraging wider adoption, as opposed to requiring verifiers to implement every possible securing method. Note that this does not mean that there are only two options; each of the two options comes with its own cryptographic algorithms and strategies.

### Can we support both?

The W3C VC specification states that:
> These two classes of securing mechanisms are not mutually exclusive.

This means that we can support both for the same VC but that needs to be explicitly specified.

### Issues

I have outlined some of the potential issues associated with Data Integrity Proofs [here](https://github.com/creator-assertions/identity-assertion/issues/73).

### Inquiry

What are the group's recommendations regarding the choice of securing mechanism to adopt?

**Comment by dangodb** [comment]
This discussion seems to be around VCDMv2.0. Is VCDMv1.1 also going to be supported by the spec? Microsoft and other implementers of VCs are currently following the [JWT VC Presentation profile](https://identity.foundation/jwt-vc-presentation-profile/) which is aligned to VCDMv1.1

**Comment by scouten-adobe** [comment]
Will be addressed by #167.

**Comment by scouten-adobe** [comment]
@dangodb sorry to have missed this comment before. We are not planning to support VC DM 1.1; #167 (under active discussion now) would focus us on using COSE enveloped VCs.
