### ISSUE TITLE
Organization as Named Actor

### ISSUE THREAD

**Issue by cward144** [creator-assertions/identity-assertion#129]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------

**Comment by cward144** [comment]
I wonder if there is a use case where an organization is the named actor rather than a person. For instance, suppose NYT wants to claim an asset that was produced by one of their journalists while protecting privacy of the journalist.

**Comment by wkreth** [comment]
This is where I think the [GLEIF](gleif.org) ID could be helpful.
