### ISSUE TITLE
Add section 3.2.2 Trust Registry

### ISSUE THREAD

**Issue by jacqueslatour** [creator-assertions/identity-assertion#131]
- [ x ] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------
A [trust registry](https://trustoverip.github.io/tswg-trust-registry-protocol/#term:trust-registry) is a resource that helps to bind governance (business, legal, and social mandates) for an ecosystem. A trust registry helps get the main answers that parties inside and outside of the ecosystem need to tie the governance into their own systems - both technically and on a governance (the information provided is created via a governed process).

A registry that serves as an authoritative source for trust graphs or other governed information describing one or more trust communities. A trust registry is typically authorized by a governance framework. (See also: [trust list](https://trustoverip.github.io/ctwg-main-glossary/#term:trust-list))

**Comment by scouten-adobe** [comment]
We decided instead to add "trust list" with a link to ToIP glossary entry for "trust registry."
