### ISSUE TITLE
9.1 Digital trust introduction

### ISSUE THREAD

**Issue by jacqueslatour** [creator-assertions/identity-assertion#132]
discussion:  The section should have a diamond trust model, with a 4 element as the trust registry/trust list, the "trust" actors in the system that either the issuer/holder/verifier go to to perform their trust verification tasks.

Could be a ToIP trust registry, a browser C2PA trust list, or a human doing manual trust verification based on the identifiers presented to them, if no list are available.

There are many instances of "when $actor$ trust other $actor$", it could reference the trust registry/list.

For discussion

**Comment by scouten-adobe** [comment]
Closed by #141.
