### ISSUE TITLE
9.3.2 Name Collisions

### ISSUE THREAD

**Issue by jacqueslatour** [creator-assertions/identity-assertion#133]
Name - this was confusing to me, but it's the natural person name, the human name "John Smith".

Rename to "Person Name Collisions", Natural Person Name? Human name???

This only occurs when a human consumer is doing manual trust verification, if trust lists or trust anchor are used, the john..smith@apnews.com is authentic because apnews.com is in a trust list/registry, but john..smith@ap-news.com would not be trusted because ap-news.com would not be in a trust list, I don't know how a human can distinguish between apnews.com and ap-news.com as legit or not. 

For discussion.

**Comment by scouten-adobe** [comment]
I think we've addressed this in the discussion on #128.

**Comment by scouten-adobe** [comment]
Closed by #128.
