### ISSUE TITLE
Inconsistent - and _ in 5.2 schema

### ISSUE THREAD

**Issue by nigelcearnshaw** [creator-assertions/identity-assertion#143]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------
Are the string names deliberately either - or _? I may just be misunderstanding the style?

hash-map, signer-payload-map in the schema, then signer-payload-map in the text along with signer_payload.sig_type. 
5.2 

expected-countersigner-map = {
  "partial_signer_payload": $signer-payload-map ; signer_payload map from other identity assertion minus any `expected_countersigner` field
  ? "expected_credentials": $hash-map ; expected identity assertion credentials
}

Should it be the following? 
expected-countersigner-map --> expected_countersigner_map
signer-payload-map -> signer_payload_map
'expected_countersigner' field -> 'expected_countersigner_map' field

**Comment by scouten-adobe** [comment]
This is intentional and follows the style used in the C2PA Technical Specification:

`field_names` are written using `snake_case`.
`type-names` are written using `kebab-case`.
