### ISSUE TITLE
Describe how to document social media account ownership in VCs

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/identity-assertion#15]
Describe how to document ownership of social media accounts in actor VC

Xref: https://creator-assertions.github.io/identity/0.1-draft/index.html#describe-social-media.

**Comment by scouten-adobe** [comment]
Make sure there is a mechanism to cover retraction of social media account ownership in the case where access to an account is compromised.

**Comment by scouten-adobe** [comment]
Ideally this should support description of multiple accounts.

**Comment by mrbao** [comment]
I wonder if there's a benefit in decentralized verification, akin to the discussions happening in the fediverse: https://github.com/mastodon/mastodon/discussions/20160

**Comment by scouten-adobe** [comment]
Done in current 1.1 draft. Closing.
