### ISSUE TITLE
Write section on proofs

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/identity-assertion#155]
Write section on proof methods.

See https://creator-assertions.github.io/identity/1.x+vc-draft/#issue-155.

**Comment by scouten-adobe** [comment]
IMS team prefers to use JOSE or COSE signing as they are generally simpler. https://www.w3.org/TR/vc-jose-cose/

Haven't yet chosen between those.

JOSE signatures more widely adopted, but have more room for errors.

**Comment by scouten-adobe** [comment]
Benefit to COSE: Already used in C2PA.

**Comment by 1livv** [comment]
After reading a bit on the matter my thoughts are :

-   support all the 3 methods defined in https://www.w3.org/TR/vc-jose-cose/
-   we could define syg_type values for each of the 3 
-   have a recommendation that COSE should be preferred due to its already prevalent usage across the c2PA ecosystem 

Right now on the IMS side we're 90% sold to COSE

**Comment by cyraxx** [comment]
As discussed in today's meeting, I'm in favor of supporting only COSE to keep the number of different code paths on the verifier's side low.
(Side note: I'm in favor of keeping specifications as tight as feasibly possible in general – IMHO allowing multiple types of serialization often removes little complexity in the implementation of the writer compared to the complexity it adds on the reader's side plus testing, providing sample files, and handling edge cases in each of the different implementation paths. Especially when cryptography is involved.)

The point was made during the meeting that some implementers might have other signature types ready to go and restricting the spec to COSE would complicate things for them. I'm wondering how likely it is that someone would be implementing serialization of creator assertions on this level who isn't also implementing C2PA and therefore would already be familiar with COSE? (Not implying anything here – maybe it _is_ likely.)

**Comment by scouten-adobe** [comment]
@cyraxx I'm inclined to agree with you here. (Fewer options are preferred.) We'll discuss #167 which only permits COSE envelopes.
