### ISSUE TITLE
Change links to version 2.0 of C2PA signature methodology to version 2.1 

### ISSUE THREAD

**Issue by puhley** [creator-assertions/identity-assertion#164]
There are significant differences between versions 2.0 and version 2.1 with regards to digital signatures and timestamp validation. Given the significant differences, we should probably link to version 2.1 of the C2PA spec. The 2.1 version  of C2PA is currently in draft status, but the time difference will probably be only one or two weeks between when CAWG 1.0 launches and C2PA 2.1 is ratified. It is unlikely that any time difference between the launch date of CAWG 1.0 spec and the C2PA 2.1 being ratified will have any real world impact.

- [X] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------

**Comment by scouten-adobe** [comment]
Closed by #166.
