### ISSUE TITLE
Define a way to prove control over a web site / domain and link it to identity claims aggregation

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/identity-assertion#177]

**Comment by scouten-adobe** [comment]
Separate, but related question: What about content credentials for generated web sites?

**Comment by christianpaquin** [comment]
It would be useful to consider control of a web path and not just web domain (e.g., example.com/user_xyz). Many content signers live in such systems, e.g., academics (university.edu/researcher_name), professionals (company_name.com/employee_name), individual contributors (blog_platform.com/blogger_name).

**Comment by scouten-adobe** [comment]
From 16 September 2024 CAWG meeting, some additional points to consider:

* Review Mastodon and AT protocol (Bluesky) for proving control over a domain for social media purposes ([Documentation for AT protocol technique](https://atproto.com/guides/identity))
* Token in meta tag or DNS record
* CA / Browser Forum guidelines for issuance and management of Extended Validation Certificates §3.2.2 covers assurance that a web site is controlled by the specific legal entity described in the cert
* I believe the OpenID community long ago did a spec for "site claiming" so that a blog owner could prove control of a blog to an OpenID provider.
* `did:web` may provide a mechanism for this, too

**Comment by scouten-adobe** [comment]
Closing in favor of #188.
