### ISSUE TITLE
Define identity assertion trust model

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/identity-assertion#22]
Add language that clarifies that the identity assertion introduces a second trust triangle, distinct from the trust triangle including the claim generator, that enables the C2PA Manifest Consumer to make trust decisions regarding the actor whose credential was used to generate the signature in this identity assertion.

Describe the trust signals that are intended to be conveyed by this assertion. Adapt from or possibly reference the following documents:

* [§6.3. Trust model](https://c2pa.org/specifications/specifications/1.3/guidance/Guidance.html#_trust_model) in C2PA implementers guidance (version 1.3)
* [§14. Trust model](https://c2pa.org/specifications/specifications/2.0/specs/C2PA_Specification.html#_trust_model) in C2PA technical specification
* [§2.2 Trust model](https://c2pa.org/specifications/specifications/1.0/security/Security_Considerations.html#_trust_model) in C2PA security considerations
* [§1.2 Ecosystem Overview](https://www.w3.org/TR/vc-data-model/#ecosystem-overview) in W3C verifiable credentials spec
* [§1.3 Use Cases and Requirements](https://www.w3.org/TR/vc-data-model/#use-cases-and-requirements) in W3C verifiable credentials spec

Xref: https://creator-assertions.github.io/identity/0.1-draft/index.html#define-trust-model.

**Comment by christianpaquin** [comment]
I'd suggest allowing a lightweight approach where the owner of a web domain (or fixed path) could create a self-signed cert, make its public key available at (something like) `<web domain>/.well-known/c2pa.jwks`, allowing anyone to fetch the key at validation time and make their own trust decision based on the web domain itself. This would allow scaling C2PA to entities (individuals and organizations) that are not part of an organized trust framework to self-sufficiently create identity assertions. A validator would present status message such as "this asset has been signed by `example.com`".

**Comment by jacqueslatour** [comment]
Just getting up to speed here, but we can contribute to the trust model.  The document link below is our current guidance and direction that aligns with the work in ToIP Trust Registry task force.  Our work aligns with Christian's comment above. More to come.

- https://www.cira.ca/uploads/2023/12/12222023_A-trust-layer-for-the-internet-is-emerging_-report-%E2%80%93-Continuum_CIRA.pdf

**Comment by scouten-adobe** [comment]
Some comments split off into new (smaller) issues. Closing this issue in favor of PR #99.
