### ISSUE TITLE
Describe credential holder’s role in relation to the asset

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/identity-assertion#26]
The now-deprecated [`stds.schema-org.CreativeWork` assertion](https://c2pa.org/specifications/specifications/1.3/specs/C2PA_Specification.html#_creative_work) offered many options.

See also: [schema.org CreativeWork schema](https://schema.org/CreativeWork).

Xref: https://creator-assertions.github.io/identity/#describe-actor-role.

**Comment by scouten-adobe** [comment]
Per @OR13, W3C VC version 2 has this: https://www.w3.org/TR/vc-json-schema/.

**Comment by scouten-adobe** [comment]
@OR13 will add other related resources.

**Comment by OR13** [comment]
We've used this in:

- https://github.com/w3c-ccg/traceability-vocab

Issuer's tend to define their own schemas, when they define their credential types.

Have to be aware of how the schema impacts the ability to present the credential:

(OpenID4VP PresentationExchange also uses JSON Schema)... but JSON Schema is not great for CBOR...

- https://docs.google.com/document/d/10JT--pXWsfwC4QVu3XJpXGwcO08M6tnpkZ4PKdtCEWo/edit#heading=h.7igj7m3na8ru

CDDL is good for CBOR, but not great for JSON.

**Comment by scouten-adobe** [comment]
Per @andyrosenms, [09:30] Andy Rosen
NDR online at https://doi.org/10.5594/M001710   or just email me  -  I have the author's enthusiastic permission to circulate this in our groups
