### ISSUE TITLE
Word Choice: "identity assertion may not refer to itself"

### ISSUE THREAD

**Issue by RicardoBochnia** [creator-assertions/identity-assertion#49]
In section 5 it is stated that:

> The list of [referenced assertions](https://creator-assertions.github.io/identity/0.1-draft/#_referenced_assertions) in the referenced_assertions field of the [identity assertion](https://creator-assertions.github.io/identity/0.1-draft/#_identity_assertion) is necessarily a subset of the assertions listed in the assertions field of the [C2PA claim](https://creator-assertions.github.io/identity/0.1-draft/#_c2pa_claim) because the [identity assertion](https://creator-assertions.github.io/identity/0.1-draft/#_identity_assertion) **may not** refer to itself.

>The referenced_assertions entry of an [identity assertion](https://creator-assertions.github.io/identity/0.1-draft/#_identity_assertion) MAY reference any other [identity assertion](https://creator-assertions.github.io/identity/0.1-draft/#_identity_assertion). Since every assertion referenced by an [identity assertion](https://creator-assertions.github.io/identity/0.1-draft/#_identity_assertion) must not change once presented to the [credential subject](https://creator-assertions.github.io/identity/0.1-draft/#_credential_subject) for signature, **care must be taken to ensure that no [identity assertion](https://creator-assertions.github.io/identity/0.1-draft/#_identity_assertion) references itself** and that no cycle of references among [identity assertions](https://creator-assertions.github.io/identity/0.1-draft/#_identity_assertion) is created.

Shouldn't it be _must not_ in the first paragraph? An identity assertion should never reference itself or am I missing something?

**Comment by scouten-adobe** [comment]
@RicardoBochnia thank you for flagging this. When you have a moment, please review #71 which aims to clarify that wording.
