### ISSUE TITLE
Ensure that time stamps are properly linked to identity assertion signatures

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/identity-assertion#54]
@OR13 raised the issue that signatures can be back-dated without some form of counter-signature that verifies time of issuance.

Adding this issue to ensure we address that before VC portion of spec is approved.

**Comment by scouten-adobe** [comment]
@OR13 my sense is this is sufficiently covered by the recommendation to use RFC 3161 countersignatures when doing COSE signatures. Based on that, I'm assigning this to the 1.x-add-w3c-vc milestone. Do you agree?

**Comment by OR13** [comment]
I'd prefer to see CDDL, and EDN examples for how to include the timestamps.

There is alsohttps://datatracker.ietf.org/doc/html/rfc9338

I'm not sure what the objective is here, so it's hard to know if it's been accomplished.

It can probably be addressed later.

**Comment by scouten-adobe** [comment]
Duplicate of #64.
