### ISSUE TITLE
Explicitly state what is being signed in an identity assertion

### ISSUE THREAD

**Issue by paulengland** [creator-assertions/identity-assertion#62]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------

Presumably something like "The signature is formed over the canonical CBOR serialization of the referenced_assertions field"

Also: Should we call the envelope "identity-map" for uniformity?

**Comment by paulengland** [comment]
A more future-proof method might be to define an identity-assertions-tbs (to be signed) map that contains referenced_assertions so that it's less disruptive if we ever want to add new data to the stuff signed by an identity signer.   See, for example, https://github.com/creator-assertions/identity-assertion/issues/65

**Comment by scouten-adobe** [comment]
Related to #68

**Comment by scouten-adobe** [comment]
I believe this was addressed by #75. Closing as completed.
