### ISSUE TITLE
Possible interaction in "multiple step processing"

### ISSUE THREAD

**Issue by paulengland** [creator-assertions/identity-assertion#63]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------
The C2PA main spec describes multi-step processing to minimize padding.  I'm not sure that this will work if an identity assertion has already encoded/fixed file offsets

**Comment by scouten-adobe** [comment]
Wording is not entirely clear. Also revisit with @lrosenthol to ensure that C2PA spec itself is sufficiently clear.

**Comment by scouten-adobe** [comment]
Follow up with C2PA 2.0 specification to ensure that it supports cases where file offsets are required. This may be more of a C2PA issue.

**Comment by paulengland** [comment]
I filed an issue against the main spec for this: https://github.com/c2pa-org/specs-core/issues/1234

We may or may not want to have text in this spec similar to https://github.com/c2pa-org/specs-core/issues/1234 in the ID assertion spec.  We may also want to have a note in this spec like:

NOTE:
For some asset file/container formats and content binding assertions, the file layout may no longer be changeable after the ID assertion is signed.  Claim Generators should ensure that sufficient padding is available so that no major changes to the file layout are needed once the first ID assertion has been signed.

**Comment by scouten-adobe** [comment]
I think we've addressed the CAWG portion of this with #119 and the remainder rightly belongs with C2PA and the issue you've filed there. Closing.
