### ISSUE TITLE
Consider stronger timestamping mechanism than W3C VC requires

### ISSUE THREAD

**Issue by paulengland** [creator-assertions/identity-assertion#64]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------

**Comment by scouten-adobe** [comment]
In X.509 section, we use the same RFC 3161 timestamp language that C2PA itself uses. This issue is valid for VCs, however, so moving it to that milestone.

**Comment by scouten-adobe** [comment]
I'm including a TO DO item with a link to this issue in an update to the 1.x draft version of the spec.

**Comment by scouten-adobe** [comment]
FYI major changes in C2PA timestamping requirements from 2.0 to current 2.1 draft.

**Comment by scouten-adobe** [comment]
Tentatively, given that we're looking at COSE signatures for VCs as well, consider placing RFC 3161 signature in COSE protected headers (similar to what's been added to C2PA 2.1).

**Comment by scouten-adobe** [comment]
Closing. Discussion moved to #192.
