### ISSUE TITLE
Identity signers cannot sign "dc:title"

### ISSUE THREAD

**Issue by paulengland** [creator-assertions/identity-assertion#65]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------

I believe that the "main" C2PA signature is for machine generated/validatable data.  dc:title (in claim-map-v2) is most likely human-generated.  Should it be in a field covered by an identity signature not a claim signature?

**Comment by scouten-adobe** [comment]
@lrosenthol should this be moved to C2PA discussion?

**Comment by scouten-adobe** [comment]
Per discussion in 11 March meeting, closing this issue.
