### ISSUE TITLE
Bidirectional binding of identity assertions and claims

### ISSUE THREAD

**Issue by paulengland** [creator-assertions/identity-assertion#67]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------

If a claim hashes an identity assertion - presumably as part of the gathered assertions - then the identity assertion is tamper-protected, but the converse is not true: an attacker can strip the claim signature and replace it without a validation failure.  This can be problematic for some scenarios: for example, a claim signature from a phone could be replaced by a signature from an editing suite.

Fundamentally, I think the binding is the wrong way around: it makes much more sense for the publisher (e.g., me) to commit to the claim-generator/tool that they used, not the other way around. 

We could add band-aids - e.g., identity assertions contain the public key of the (subsequent) claim signer, but I think we should have a conversation about whether this is really the right way of doing this.

Similar arguments/problems occur in the case of multiple ID assertions: later assertions can be bound to ID assertions created earlier, but later ID assertions can be replaced without a validation failure.

**Comment by walkerlj0** [comment]
ZKP can be used to validate identity (but having holder of identity sign with a private key) without revealing any information about that identity (name, location, biometric info, etc) for a credential holder.

_What are the reasons for anonymous Identity for Holders of credential?_

    - Journalists who want to add claims or make edits to photos, but may be in a place where if their identity is revealed, they are put at risk.
    - OSINT (OS investigators) who may want to report but again, if their location is revealed, it could put their safety at risk
    - Whistleblowers who want to report on governmental, institutional, or other wrongdoing but not put their jobs or safety at risk.
    - Anyone else who may want to make a claim and bind their identity to a claim, and not reveal their identity until a later date, such as during a court case, or if copyright is claimed.
     
_Risks_
- Digital Interception and revealing of information about media creator 
- Physical seizure of assets at border crossings
- Unwanted leakage of information that reveal PII
- Individuals or organizations claiming rights to work or creations they didn’t capture or create
- Authenticity being called into question (claims that some important and influential piece of media is fake when it is not)


_Considerations_
Who Issues identity? (who manages IAM or KYC?)
Can we make this ^  decentralized?
What ZK Proofs have been used for this before?
Have ZK Proofs been vetted for security or vulnerability? (e.g. a small amount of info is revealed, and opens a door for inference of other data through an attack)

**Comment by scouten-adobe** [comment]
@scouten-adobe to provide write access to @paulengland

**Comment by scouten-adobe** [comment]
Closing in favor of #95.
