### ISSUE TITLE
Is the ID assertion TBS-data expressive enough?

### ISSUE THREAD

**Issue by paulengland** [creator-assertions/identity-assertion#68]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------

Claims have a couple of text fields that can be used to provide info about the claim generator.  Do we need something similar for ID assertions?  For example, if a manifest contains three ID assertions by three different key-holders, should we provide a field to (e.g.,) encode what role these signers are playing? (fact checker, editor, journalist...)

**Comment by scouten-adobe** [comment]
See also #26.

**Comment by scouten-adobe** [comment]
Perhaps one of the additional fields is a human-readable statement of intent behind the edits.

**Comment by scouten-adobe** [comment]
PR #75 introduced a to-be-signed data structure; after that, I think #26 describes the need for the credential subject's role to be documented. Closing as redundant.
