### ISSUE TITLE
VCs credentialSubject.id field's purpose?

### ISSUE THREAD

**Issue by rghiorghisor** [creator-assertions/identity-assertion#83]
- [x] I have read the [CLA Document](https://github.com/creator-assertions/identity-assertion/blob/main/contributor-license.md) and I hereby sign the CLA.

----------------------------------------
As VPs are out of discussion, what will be the purpose, if any, of the `credentialSubject.id` property in VCs?
In VPs this URI could be use to get the verification material to verify the subjects signature (e.g. use a DID to get the DID Document that contains the `verificationMethod`). But, as this is not needed anymore, **what should their purpose be**?

Per [A.1 Credential Subject](https://www.w3.org/TR/vc-data-model/#credential-subject-0) section of [W3C Verifiable Credentials](https://www.w3.org/TR/vc-data-model/) specification:
> The id [property](https://www.w3.org/TR/vc-data-model/#dfn-property) is optional. [Verifiers](https://www.w3.org/TR/vc-data-model/#dfn-verifier) could use other [properties](https://www.w3.org/TR/vc-data-model/#dfn-property) in a [verifiable credential](https://www.w3.org/TR/vc-data-model/#dfn-verifiable-credentials) to uniquely identify a [subject](https://www.w3.org/TR/vc-data-model/#dfn-subjects).

**Comment by scouten-adobe** [comment]
@rghiorghisor please see #85. I'm proposing completely new language around VCs.

**Comment by scouten-adobe** [comment]
We've recently deleted the `id` field. Closing.
